language: node_js
node_js:
  - 10
script:
  - npm run build
  - cd functions
  - npm ci
  - cd ..
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: SPBzE1g1qhR4JfovR8H3D2qIPwhXl3d06i1JEzmQgnoqF9Qhhg7atliPEi41X4ctTlqIzkFo6/9lthdKN/eUwS37kn6SrXNlbzAw9etIJez+xvKOxf5onjtXAWkKoabIJDkW21hhDgozeE7DK8X3y9ZPUb5ZxuWfKlDBVoo/PAtqvwmfoB2UBnnQl/iWHOQmbyq0GtmdR2/TxqHTnOWHTW7V6pMUT2KZrzbYvZP0uKPHUD8/2Ax6CeNimw5hn7s9u+jUZpeKzfgwg/CqgLP+e7bGMQ3wGSegBFQYH6vuUwzGJNR0hPElgPPZN0Sqv7JFwmNiqUVHrijxnLaqpv+wOmtpTbIR2txjiLxpWHz9eedDC2YQZe1gpyTo2MCOTsS+0CeZG2rHPuJykzA49wzJLQwfw/+eRP+lLHw3tw07ys1/ooI8XcV9OE+Wpd6IaDPkxCrZyjoT9p+ZvqdddEL53bqBjO7XODRsS1NfS7WYoJAq5tdEd3WsBahP2L9vacQJLg4mWyYGylN+c1CaOoleq3Z1w7Bfz/KIi/RM+faI58FNGxGCIs++yoGcJOikGF9UJa92TY7r27UJVkGxHCmmWjgvlsu7ZLPgNeQ/w/LbQsSlGl8ejRhTFfHbCVBtT6rhtRfRqaqxZXIFca4rhKj4c6DmaEzlQRbneigWhgU9O2Q=
