language: node_js
node_js:
  - 10
script:
  - npm run build
  - cd functions
  - npm ci
  - cd ..
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: iup5+jPQFMIhb6SiHgKd8e/sP5mNO8sxNEPvU8gKOtKMINm7PJx+vKhe5tCDoJh/jlVHszGEuwvWvPIPtCKv6jvskgqaKdCn/Q2sb/xKfzwH3T6vjBvOLIqBbJMi48zW5FnUCjCgxkRm3R6hx4rRy7n6nB6XGh85oVyH9Uhp3Y6B/MajvWcQ/sRFsSYObeZeTH19eZ976Qs9S0N4G0XQjSbySocggA4ckCvFIAGtJLVoiv8asitHOPj8LIQ4tFGx/59L+lQiptGjapGte5G4FEHQT/TKPL5Jf39iddPZVH9argyKYYWZPSP22R59qg+1l19HZF0EDKSeuaV9Td8hOLl/TRaFuoJonOAtZ4S1pKRI8rGKGExKW6eT90cT9A8NkC+BQbCeWqx5JYndJxvSoeBKXHvWZfw+G6ygTmo+qe/fE7cTTWT84LKXlqyw1SjhCeOMiQOumhujyu9mTkkVA8BG7M7ICbIIWnPBm+zOhhsvWJ3sfH9xgHMiy9BjlQHtZ0REKqEmBPY31dNHaWknDb+v2c47vQ3lnhA5D3QioO1A6OMiD2MJwvJi1cueOD9PyJAE5azDKoLF+Uzw3gFEj8Ru0nDPK9Hfg1hmboP1k+5kb78/Up182SUrY/Qudb6bgUw11yyVRK3UOdnEvsJGQjfVSVhAwQPvR6OiMFlg3Rs=
