name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Build Functions
        working-directory: functions
        run: |
          npm ci
          npm run build
      - name: Firebase Deploy
        run: |
          npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
